# Generated by Django 4.2.3 on 2023-07-21 13:25

import DjangoExamProject.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), DjangoExamProject.core.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), DjangoExamProject.core.validators.validate_only_letters])),
                ('specialization', models.CharField(choices=[('surgeon', 'Surgeon'), ('cardiologist', 'Cardiologist'), ('gynecologist', 'Gynecologist'), ('urologist', 'Urologist'), ('dermatologist', 'dermatologist'), ('neurologist', 'neurologist'), ('DoNotShow', 'Do not show')], max_length=13)),
            ],
        ),
    ]
